version: "3.6"
services:
  db:
    build: docker-db/
    restart: always
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD
      - POSTGRES_DB=otohime
      - POSTGRES_DB_USER=otohime
      - POSTGRES_DB_PASSWORD
    volumes:
      - dbdata_16:/var/lib/postgresql/data
    shm_size: 256mb
  hasura:
    image: hasura/graphql-engine:v2.45.1-ce
    ports:
      - "127.0.0.1:8580:8080"
    depends_on:
      - "db"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://otohime:${POSTGRES_DB_PASSWORD}@db:5432/otohime
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_DEV_MODE: "${HASURA_DEV_MODE}"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET}"
      HASURA_GRAPHQL_AUTH_HOOK: http://hooks:8787/auth/
      HASURA_GRAPHQL_ENABLED_APIS: "${HASURA_GRAPHQL_ENABLED_APIS}"
  hooks:
    build: hooks/
    depends_on:
      - "db"
      - "hasura"
    environment:
      FIREBASE_ID: ${FIREBASE_ID}
      SEGA_ID: ${SEGA_ID}
      SEGA_PASSWORD: ${SEGA_PASSWORD}
      PGUSER: otohime
      PGDATABASE: otohime
      PGHOST: db
      PGPASSWORD: ${POSTGRES_DB_PASSWORD}
volumes:
  dbdata_16:
