# https://github.com/docker-library/postgres/issues/175

file_env 'POSTGRES_DB_USER'
file_env 'POSTGRES_DB_PASSWORD'

if [ "$POSTGRES_DB_USER" ] && [ "$POSTGRES_DB_PASSWORD" ] && [ "$POSTGRES_DB" ]; then
	docker_process_sql <<-EOSQL
	CREATE ROLE "$POSTGRES_DB_USER" WITH NOSUPERUSER LOGIN PASSWORD '$POSTGRES_DB_PASSWORD';
	GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_DB" TO "$POSTGRES_DB_USER" ;
	CREATE EXTENSION IF NOT EXISTS pgcrypto;
	CREATE EXTENSION IF NOT EXISTS btree_gist;
	CREATE EXTENSION IF NOT EXISTS periods;

	-- Hasura requiremenets
	CREATE SCHEMA IF NOT EXISTS hdb_catalog;
	CREATE SCHEMA IF NOT EXISTS hdb_views;
	ALTER SCHEMA hdb_catalog OWNER TO "$POSTGRES_DB_USER";
	ALTER SCHEMA hdb_views OWNER TO "$POSTGRES_DB_USER";

	GRANT SELECT ON ALL TABLES IN SCHEMA information_schema TO  "$POSTGRES_DB_USER";
	GRANT SELECT ON ALL TABLES IN SCHEMA pg_catalog TO "$POSTGRES_DB_USER";
	GRANT USAGE ON SCHEMA public TO "$POSTGRES_DB_USER";
	GRANT ALL ON ALL TABLES IN SCHEMA public TO "$POSTGRES_DB_USER"; 
	GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO "$POSTGRES_DB_USER"; 
	GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO "$POSTGRES_DB_USER"; 
	EOSQL
else
	echo "Please set POSTGRES_DB_USER, POSTGRES_DB_PASSWORD and POSTGRES_DB."
fi